version: "3.8"

services:
  postgres:
    container_name: miniland-postgres
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: miniland
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
  keycloak:
    image: jboss/keycloak
#    image: sleighzy/keycloak
    container_name: miniland-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: miniland
      DB_USER: k_app
      DB_PASSWORD: 123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
  miniland-server:
    image: miniland-server
    container_name: "miniland-server"
    environment:
      JAR_FILE: build/libs/*.jar
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/miniland
      SPRING_DATASOURCE_USERNAME: k_app
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
    ports:
      - "8181:8181"
    links:
      - "keycloak:keycloak"

