application:
  title: MiniLand
  version: 1.0.0
  delete-all-files: true
  keycloak-url: ${KEYCLOAK_URL:http://34.146.23.123/keycloak}
#  keycloak-url: ${KEYCLOAK_URL:http://192.168.0.101:8484/auth}
#  keycloak-url: ${KEYCLOAK_URL:http://172.20.10.11:8484/auth}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:miniland}
    username: ${DATABASE_USERNAME:k_app}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak-url}/realms/miniland
          jwk-set-uri: ${application.keycloak-url}/realms/miniland/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
jwt:
  auth:
    converter:
      resource-id: miniland
      principle-attribute: preferred_username

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: 8181
  address: 0.0.0.0

