name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag miniland-server

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login --username ${{ env.DOCKERHUB_USERNAME }} --password-stdin

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push miniland-server
