name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag miniland-server
      
    - name: test
      run: echo ${{secrets.DOCKERHUB_TOKEN}} ${{secrets.DOCKERHUB_TOKEN}}
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push miniland-server


